{"name": "Ввод плохого ключа должен выводить ошибку", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: \n\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/step_license.py\", line 34, in step_impl\n    context.browser.get(appAddress(context) + path)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 165, in check_response\n    raise exception_class(value)\n"}, "steps": [{"name": "Допустим открыли мы страницу платформы /dashboard/login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: \n\n", "trace": "  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1456, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.6/site-packages/behave/model.py\", line 1903, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/step_license.py\", line 34, in step_impl\n    context.browser.get(appAddress(context) + path)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 320, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 308, in execute\n    self.error_handler.check_response(response)\n  File \"/usr/local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 165, in check_response\n    raise exception_class(value)\n"}, "start": 1510126894970, "stop": 1510126985019}, {"name": "И это оказалась страница ввода лицензии", "status": "skipped", "start": 1510126985020, "stop": 1510126985020}, {"name": "Если мы вводим invalid_key в качестве ключа для пользователя test_user@directual.com", "status": "skipped", "start": 1510126985020, "stop": 1510126985020}, {"name": "То отображается ошибка", "status": "skipped", "start": 1510126985020, "stop": 1510126985020}], "start": 1510126894958, "stop": 1510126985020, "uuid": "37468ab9-965c-43fe-b0de-5a57871e68bf", "historyId": "1d2869dfbbc20e42cefcb0d0a1eeb0e8", "labels": [{"name": "severity", "value": "minor"}, {"name": "feature", "value": "Лицензионные ключи и вход в систему"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}